services:
  pixagram:
    # build: .
    image: charliereign/pixagram
    ports:
      - 80:80
    # env_file:
    #   - .env
    # environment:
    #   - FRONT_END_BASE_URL=http://localhost:3000
    #   - SQLALCHEMY_DATABASE_URL=sqlite:///./insta.db
    #   - SECRET_KEY=77407c7339a6c00544e51af1101c4abb4aea2a31157ca5f7dfd87da02a628107
    #   - ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=5