apiVersion: v1
kind: Service
metadata:
  name: pixagram
spec:
  selector:
    app: pixagram
  ports:
  - port: 1993
    targetPort: 1993
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixagram
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pixagram
  template:
    metadata:
      labels:
        app: pixagram
    spec:
      containers:
      - name: pixagram
        image: charliereign/pixagram
        imagePullPolicy: Always 
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 1993
